# Numpy

Why use numpy
- powerful
- speed
- collection of item
- item mutable/editable
- Support Data Science

In [1]:
a = [10, 20, 30, 40, 50]

In [2]:
b = [5, 5, 10, 10, 25]

In [3]:
a / b

TypeError: unsupported operand type(s) for /: 'list' and 'list'

## here comes Numpy

In [4]:
import numpy as np

In [5]:
a = np.array([10, 20, 30, 40, 50])
b = np.array([5, 5, 10, 10, 25])

In [6]:
a / b

array([2., 4., 3., 4., 2.])

## Numpy remarks

In [7]:
python_list = [1,2,3]

In [8]:
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [9]:
numpy_array = np.array([1,2,3])

In [10]:
numpy_array + numpy_array

array([2, 4, 6])

## Numpy subsetting 

We have list [73, 60, 80, 85, 70, 90] <br>
We want to know which has value more than 75

In [11]:
student_marks = np.array([73, 60, 80, 85, 70, 90])

In [12]:
student_marks > 75

array([False, False,  True,  True, False,  True])

In [13]:
student_marks[student_marks > 75]

array([80, 85, 90])

## Numpy and Basic Statistics

In [14]:
x = np.round(np.random.normal(1.75, 0.20, 5000), 2)
y = np.round(np.random.normal(60.32, 15, 5000), 2)

# np.random.normal(distribution_mean, distribution_standard_deviation, sample_count)

In [16]:
z = np.column_stack((x,y))

In [17]:
z

array([[ 2.11, 46.79],
       [ 1.86, 40.68],
       [ 1.95, 46.99],
       ...,
       [ 1.63, 51.4 ],
       [ 1.75, 84.58],
       [ 1.5 , 83.23]])

In [23]:
np.mean(z[:,0])

1.7466

In [24]:
np.mean(z[0,:])

24.45

In [25]:
np.median(z[:,0])

1.745

In [26]:
np.corrcoef(z[:,0], z[:,1])

array([[1.        , 0.00275242],
       [0.00275242, 1.        ]])

In [27]:
np.std(z[:,0])

0.2020540521741645